### PR TITLE
Add input support (part 1)

### PR DESCRIPTION
**Pull request by hello-smile6**
I needed to add partial support for Freecat's settings page. (I thought I made this PR yesterday, turns out I just made a PR from the branch on my fork to my fork's main branch).

### CODE REVIEW

**Comment by MystPi** [comment]
Sorry for being nit picky, but could you add newlines around the `input` styling? I can't edit your PR.

**Comment by hello-smile6** [comment]
> Sorry for being nit picky, but could you add newlines around the `input` styling? I can't edit your PR.

Sure.

**Comment by hello-smile6** [comment]
> Sorry for being nit picky, but could you add newlines around the `input` styling? I can't edit your PR.
Giving you edit access

**Comment by hello-smile6** [comment]
@MystPi You now have edit access.

**Comment by MystPi** [comment]
Thanks for contributing!

**Comment by hello-smile6** [comment]
> Thanks for contributing!

You're welcome!

**Pull request merged**
